name: Build Docker Image
on:
    push:
        branches:
            - main
        paths:
            - "Cargo.toml"

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Check out Source Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - name: Version Change
              id: version_check
              run: |
                  if git diff HEAD~1 -- Cargo.toml | grep -q '^+version = '; then
                    echo "version_changed=true" >> $GITHUB_OUTPUT
                    current_version=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
                    echo "current_version=$current_version" >> $GITHUB_OUTPUT
                  else
                    echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi
            - name: Build Docker Image
              if: steps.version_check.outputs.version_changed == 'true'
              run: |
                  docker build --build-arg DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}' --build-arg YOUTUBE_TOKEN='${{ secrets.YOUTUBE_TOKEN }}' -t mercury .
                  docker images
                  docker save --output mercury.tar mercury:latest
            - name: Upload Docker Image to tyc-imac Server
              if: steps.version_check.outputs.version_changed == 'true'
              env:
                  SSH_URL: ssh.mercuryland.pp.ua
                  # 從 GitHub Secrets 讀取 Service Token
                  CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
                  CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
                  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  # 1. 搞到金鑰
                  echo $PRIVATE_KEY > ssh-key
                  chmod 600 ssh-key

                  # 2. 安裝與驗證 cloudflare tunnel
                  # 下載並安裝 cloudflared 執行檔
                  curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
                  sudo dpkg -i cloudflared.deb

                  # 3. 使用 ProxyCommand 穿透隧道並上傳
                  # 注意：我們透過 -o ProxyCommand 讓 SSH 流量經過 cloudflared access 並帶上 Token
                    scp -o "ProxyCommand=cloudflared access ssh \
                            --hostname $SSH_URL \
                            --service-token-id $CF_CLIENT_ID \
                            --service-token-secret $CF_CLIENT_SECRET" \
                      -i ssh-key \
                    mercury.tar champsing@$SSH_URL:~/custom_apps/mercury/

                  # 4. 遠端執行 Docker 指令
                    scp -o "ProxyCommand=cloudflared access ssh \
                            --hostname $SSH_URL \
                            --service-token-id $CF_CLIENT_ID \
                            --service-token-secret $CF_CLIENT_SECRET" \
                        -i ssh-key \
                    champsing@$SSH_URL "cd ~/custom_apps/mercury && docker load -i mercury.tar && ../restart_docker_compose.sh"
