name: Pull Request Check (Docker)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - ".dockerignore"

jobs:
  docker:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Build
        run: docker build --build-arg DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -t mercury .
