name: Pull Request Check (Backend)
on:
  pull_request: 
    types: [opened, synchronize, reopened]
    branches: main
jobs:
  rust:
    name: Test Rust
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust Toolchain
        run: rustup toolchain add nightly
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Test
        run: cargo test
  docker:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t mercury .