name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.pull_request.changed_files &&
          (contains(github.event.pull_request.changed_files, 'Cargo.toml') ||
           contains(github.event.pull_request.changed_files, 'Cargo.lock') ||
           startsWith(github.event.pull_request.changed_files, 'src/')) }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Test
        run: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} cargo test

  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.pull_request.changed_files &&
          (contains(github.event.pull_request.changed_files, 'Dockerfile') ||
           contains(github.event.pull_request.changed_files, 'docker-compose.yml') ||
           contains(github.event.pull_request.changed_files, '.dockerignore')) }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Build
        run: docker build --build-arg DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -t mercury .

  vue_js:
    name: Vue.js
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.pull_request.changed_files &&
          (startsWith(github.event.pull_request.changed_files, 'web/') ||
           startsWith(github.event.pull_request.changed_files, 'public/') ||
           contains(github.event.pull_request.changed_files, 'package.json') ||
           contains(github.event.pull_request.changed_files, 'package-lock.json') ||
           contains(github.event.pull_request.changed_files, 'tsconfig.json') ||
           contains(github.event.pull_request.changed_files, 'tsconfig.node.json') ||
           contains(github.event.pull_request.changed_files, 'vite.config.ts') ||
           contains(github.event.pull_request.changed_files, 'tailwind.config.js') ||
           contains(github.event.pull_request.changed_files, 'postcss.config.js') ||
           contains(github.event.pull_request.changed_files, 'index.html')) }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Format Check
        run: npm run format:check
      - name: Type Check
        run: npx vue-tsc --noEmit
      - name: Build
        run: npm run build

  version_check:
    name: Version
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.pull_request.changed_files &&
          (contains(github.event.pull_request.changed_files, 'Cargo.toml') ||
           contains(github.event.pull_request.changed_files, 'Cargo.lock') ||
           contains(github.event.pull_request.changed_files, 'package.json') ||
           contains(github.event.pull_request.changed_files, 'package-lock.json')) }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4
      - name: Check Version Consistency
        run: |
          CARGO_VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          CARGO_LOCK_VERSION=$(grep -A 5 'name = "mercury_land"' Cargo.lock | grep '^version = ' | sed 's/version = "\(.*\)"/\1/')
          PACKAGE_LOCK_VERSION=$(jq -r '.version' package-lock.json)
          
          if [ "$CARGO_VERSION" != "$PACKAGE_VERSION" ] || [ "$CARGO_VERSION" != "$CARGO_LOCK_VERSION" ] || [ "$CARGO_VERSION" != "$PACKAGE_LOCK_VERSION" ]; then
            echo "Version mismatch:"
            echo "Cargo.toml: $CARGO_VERSION"
            echo "package.json: $PACKAGE_VERSION"
            echo "Cargo.lock: $CARGO_LOCK_VERSION"
            echo "package-lock.json: $PACKAGE_LOCK_VERSION"
            exit 1
          fi
          echo "All versions are consistent: $CARGO_VERSION"
      - name: Check Cargo.lock is up to date
        run: |
          if cargo update --dry-run 2>&1 | grep -q "Updating"; then
            echo "Cargo.lock is not up to date. Run 'cargo update' to update dependencies."
            exit 1
          fi
          echo "Cargo.lock is up to date"
      - name: Check package-lock.json is up to date
        run: |
          if npm outdated 2>/dev/null | grep -q .; then
            echo "package-lock.json is not up to date. Run 'npm update' to update dependencies."
            exit 1
          fi
          echo "package-lock.json is up to date"